<?php
require_once "../config/database.php";
require_once "../includes/functions.php";
require_role('veterinarian');
ensure_review_workflow_schema($conn);
$editableFields=['name'=>'Pet Name','species'=>'Species','breed'=>'Breed','sex'=>'Sex','birth_date'=>'Birth Date','weight'=>'Weight','color'=>'Color / Markings','allergies'=>'Allergies','critical_notes'=>'Critical Notes','notes'=>'Care Notes'];
$approvalReasons=['clinically_consistent'=>'Requested change is clinically consistent','owner_history_confirmed'=>'Owner history supports the requested change','record_supported'=>'Clinic record supports the requested change','safe_to_apply'=>'Requested change is safe to apply'];
$rejectionReasons=['needs_examination'=>'Pet needs an in-person examination','insufficient_context'=>'Clinical context is insufficient','conflicts_with_record'=>'Request conflicts with the clinic record','needs_more_proof'=>'More supporting proof is needed'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf_or_fail();
    $id=(int)($_POST['request_id']??0);$decision=$_POST['decision']??'';$reasonKey=trim($_POST['consult_reason']??'');$note=trim($_POST['vet_note']??'');
    if(!in_array($decision,['approved','rejected'],true)){flash('error','Choose a valid consultation decision.');redirect_to('vet/pet_change_reviews.php');}
    $reasonMap=$decision==='approved'?$approvalReasons:$rejectionReasons;
    if(!isset($reasonMap[$reasonKey])){flash('error','Choose a valid consultation reason.');redirect_to('vet/pet_change_reviews.php');}
    $stmt=$conn->prepare("SELECT er.*,p.name pet_name FROM edit_requests er JOIN pets p ON er.pet_id=p.id WHERE er.id=? AND er.status='pending' LIMIT 1");$stmt->bind_param('i',$id);$stmt->execute();$request=$stmt->get_result()->fetch_assoc();
    if(!$request){flash('error','This request is not available for veterinarian consultation.');redirect_to('vet/pet_change_reviews.php');}
    $vetId=(int)current_user_id();$reviewNote=$reasonMap[$reasonKey].($note!==''?' — '.$note:'');
    $update=$conn->prepare("UPDATE edit_requests SET vet_approval_status=?,vet_approved_by=?,vet_approved_at=NOW(),admin_notes=CASE WHEN admin_notes IS NULL OR admin_notes='' THEN ? ELSE CONCAT(admin_notes, '\nVet consultation: ', ?) END WHERE id=?");
    $update->bind_param('sissi',$decision,$vetId,$reviewNote,$reviewNote,$id);$update->execute();
    notify_user($conn,(int)$request['client_id'],'Pet Change Consultation','A veterinarian reviewed the requested profile update for '.$request['pet_name'].'. Consultation status: '.ucfirst($decision).'.','record',null);
    log_action($conn,ucfirst($decision).' pet change consultation','edit_request',$id,$reviewNote);flash('success','Veterinarian consultation recorded. Administrator approval is still required before the pet record changes.');
    redirect_to('vet/pet_change_reviews.php');
}
$status=$_GET['status']??'all';if(!in_array($status,['all','pending','approved','rejected','appealed'],true))$status='all';$q=trim($_GET['q']??'');[$page,$perPage,$offset]=pagination_values(4,16,[4,8,12,16,'full']);
$where=["COALESCE(er.vet_approval_status,'pending')<>'not_required'"];$types='';$params=[];if($status==='appealed')$where[]="er.appeal_status='pending'";elseif($status!=='all'){$where[]='er.status=?';$types.='s';$params[]=$status;}if($q!==''){$like='%'.$q.'%';$where[]='(u.full_name LIKE ? OR p.name LIKE ? OR er.field_name LIKE ? OR er.old_value LIKE ? OR er.new_value LIKE ?)';$types.='sssss';array_push($params,$like,$like,$like,$like,$like);}$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
$count=$conn->prepare("SELECT COUNT(*) c FROM edit_requests er JOIN pets p ON er.pet_id=p.id JOIN users u ON er.client_id=u.id $whereSql");if($types)$count->bind_param($types,...$params);$count->execute();$total=(int)$count->get_result()->fetch_assoc()['c'];
$stmt=$conn->prepare("SELECT er.*,p.name pet_name,p.species,p.pet_photo,u.full_name requester_name,u.email requester_email,v.full_name vet_name FROM edit_requests er JOIN pets p ON er.pet_id=p.id JOIN users u ON er.client_id=u.id LEFT JOIN users v ON er.vet_approved_by=v.id $whereSql ORDER BY er.appeal_status='pending' DESC,FIELD(er.status,'pending','rejected','approved'),er.created_at DESC LIMIT $perPage OFFSET $offset");if($types)$stmt->bind_param($types,...$params);$stmt->execute();$rows=[];$res=$stmt->get_result();while($r=$res->fetch_assoc())$rows[]=$r;
$summary=$conn->query("SELECT COUNT(*) total,SUM(status='pending') pending,SUM(status='approved') approved,SUM(status='rejected') rejected,SUM(appeal_status='pending') appealed FROM edit_requests WHERE COALESCE(vet_approval_status,'pending')<>'not_required'")->fetch_assoc();
$title='Pet Change Reviews';include "../includes/header.php";include "../includes/navbar.php";
?>
<div class="layout"><?php include "../includes/vet_sidebar.php";?><main class="content vet-pet-change-reviews-page" id="mainContent">
<header class="page-heading"><div><span class="eyebrow">Pet records</span><h1>Pet Change Reviews</h1></div></header>
<?php if($m=flash('success')):?><div class="alert alert-success"><?=e($m)?></div><?php endif;?><?php if($m=flash('error')):?><div class="alert alert-danger"><?=e($m)?></div><?php endif;?>
<section class="surface-card data-toolbar pet-edit-toolbar"><div class="filter-tabs"><?php foreach(['all'=>'All','pending'=>'Pending','approved'=>'Approved','rejected'=>'Rejected','appealed'=>'Appeals'] as $key=>$label):?><a class="filter-tab filter-<?=e($key)?> <?=$status===$key?'active':''?>" href="?status=<?=$key?>&q=<?=urlencode($q)?>&per_page=<?=e(per_page_value($perPage))?>"><?=e($label)?><b><?=intval($summary[$key==='all'?'total':$key]??0)?></b></a><?php endforeach;?></div><form class="toolbar-actions moved-show-control" method="GET" action="pet_change_reviews.php"><input type="hidden" name="status" value="<?=e($status)?>"><input type="hidden" name="q" value="<?=e($q)?>"><label class="entries-select">Show<select class="unified-show-select" name="per_page" aria-label="Pet edit requests per page" onchange="this.form.submit()"><?=render_per_page_options($perPage,[4,8,12,16,'full'])?></select></label></form></section>
<form class="surface-card data-search-bar" method="GET"><input type="hidden" name="status" value="<?=e($status)?>"><input type="search" name="q" value="<?=e($q)?>" placeholder="Search pet, requester, field, or value"><button class="button-primary">Search</button><?php if($q!==''):?><a class="button-secondary" href="?status=<?=e($status)?>">Clear</a><?php endif;?></form>
<div class="edit-request-grid view-grid" id="editRequestQueue"><?php if(!$rows):?><div class="empty-state surface-card"><h2>No requests found</h2><p>Try another filter or search.</p></div><?php endif;foreach($rows as $r):$fieldLabel=$editableFields[$r['field_name']]??ucwords(str_replace('_',' ',$r['field_name']));$detail=['title'=>$r['pet_name'].' · '.$fieldLabel,'eyebrow'=>'Requested by '.$r['requester_name'],'fields'=>['Old value'=>$r['old_value'],'Requested value'=>$r['new_value'],'Proof note'=>$r['proof_note']?:'No note','Status'=>ucfirst($r['status']),'Veterinarian consultation'=>ucwords(str_replace('_',' ',$r['vet_approval_status'])).($r['vet_name']?' by '.$r['vet_name']:''),'Appeal'=>ucwords(str_replace('_',' ',$r['appeal_status'])),'Clinic note'=>$r['admin_notes']?:'No note']];?>
<article class="surface-card edit-request-card field-<?=e(str_replace('_','-',$r['field_name']))?>" data-record-detail='<?=e(json_encode($detail))?>'><header><?=pet_avatar_markup($r,'entity-avatar')?><div><span class="eyebrow"><?=e($fieldLabel)?></span><h2><?=e($r['pet_name'])?></h2><p>Requested by <?=e($r['requester_name'])?></p></div><?=badge($r['status'])?></header><div class="change-comparison"><div><small>Current</small><p><?=e($r['old_value']?:'Not recorded')?></p></div><span><?=ui_icon('arrow-right')?></span><div><small>Requested</small><p><?=e($r['new_value'])?></p></div></div><div class="request-evidence"><span><b>Proof</b><?php if($r['proof_path']):?><a class="button-secondary proof-view-button" data-detail-bypass target="_blank" rel="noopener" href="<?=e(app_url($r['proof_path']))?>">View proof</a><?php else:?><small>No proof uploaded</small><?php endif;?></span><span><b>Vet consultation</b><small><?=e(ucwords(str_replace('_',' ',$r['vet_approval_status'])))?><?=$r['vet_name']?' · '.e($r['vet_name']):''?></small></span><?php if($r['appeal_status']!=='none'):?><span><b>Appeal</b><small><?=e(ucwords(str_replace('_',' ',$r['appeal_status'])))?></small><?php if($r['appeal_proof_path']):?><a class="button-secondary proof-view-button" data-detail-bypass target="_blank" rel="noopener" href="<?=e(app_url($r['appeal_proof_path']))?>">View appeal proof</a><?php endif;?></span><?php endif;?></div><?php if($r['status']!=='pending' && trim((string)($r['admin_notes']??''))!==''):?><div class="review-ui-review-reason"><b><?=e(ucfirst($r['status']))?> reason</b><p><?=e($r['admin_notes'])?></p></div><?php endif;?>
<?php if($r['status']==='pending' && $r['vet_approval_status']==='pending'):?><div class="review-decision-grid vet-consult-decision-grid"><form method="POST" class="request-review-form approve-review-form vet-approve-review"><?=csrf_field()?><input type="hidden" name="request_id" value="<?=$r['id']?>"><input type="hidden" name="decision" value="approved"><label>Approval reason<select class="form-select" name="consult_reason" required><option value="">Choose</option><?php foreach($approvalReasons as $key=>$label):?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select></label><label>Optional note<textarea class="form-control" name="vet_note" rows="2" placeholder="Add a short clinic note"></textarea></label><button class="button-primary pet-edit-approve-button vet-consult-approve" type="submit">Approve</button></form><form method="POST" class="request-review-form reject-review-form"><?=csrf_field()?><input type="hidden" name="request_id" value="<?=$r['id']?>"><input type="hidden" name="decision" value="rejected"><label>Rejection reason<select class="form-select" name="consult_reason" required><option value="">Choose</option><?php foreach($rejectionReasons as $key=>$label):?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select></label><label>Optional note<textarea class="form-control" name="vet_note" rows="2" placeholder="Add context for the client"></textarea></label><button class="button-danger" type="submit">Reject</button></form></div><?php elseif($r['vet_approval_status']!=='pending'):?><div class="review-complete"><b><?=e(ucfirst($r['vet_approval_status']))?> consultation</b><span><?=e($r['vet_approved_at']?date('M d, Y h:i A',strtotime($r['vet_approved_at'])):'')?></span></div><?php endif;?>
</article><?php endforeach;?></div><?=render_pagination($page,$perPage,$total,['status'=>$status,'q'=>$q,'per_page'=>per_page_value($perPage),'_anchor'=>'editRequestQueue'])?>

</main></div><?php include "../includes/footer.php";?>
