<?php
require_once "../config/database.php";require_once "../includes/functions.php";require_role(['admin','veterinarian','staff']);
$uid=(int)current_user_id();$role=$_SESSION['role']??'';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf_or_fail();$current=$_POST['current_password']??'';$new=$_POST['new_password']??'';$confirm=$_POST['confirm_password']??'';
 $stmt=$conn->prepare("SELECT password FROM users WHERE id=? LIMIT 1");$stmt->bind_param('i',$uid);$stmt->execute();$row=$stmt->get_result()->fetch_assoc();
 if(!$row||!password_verify($current,$row['password']))flash('error','Current password is incorrect.');elseif($new!==$confirm)flash('error','New passwords do not match.');elseif($errors=password_policy_errors($new))flash('error',implode(' ',$errors));elseif(password_verify($new,$row['password']))flash('error','Choose a password different from the current password.');else{$hash=password_hash($new,PASSWORD_DEFAULT);$stmt=$conn->prepare("UPDATE users SET password=?,password_changed_at=NOW(),failed_login_attempts=0,locked_until=NULL WHERE id=?");$stmt->bind_param('si',$hash,$uid);$stmt->execute();session_regenerate_id(true);log_action($conn,'Changed account password','user',$uid,'Password changed from the account security page.');flash('success','Password changed successfully.');}
 redirect_to('account/change_password.php');
}
$user=current_user_record($conn);$title='Change Password';include "../includes/header.php";include "../includes/navbar.php";$sidebar=$role==='admin'?'admin_sidebar.php':($role==='veterinarian'?'vet_sidebar.php':'staff_sidebar.php');
?>
<div class="layout"><?php include "../includes/$sidebar";?><main class="content" id="mainContent"><header class="page-heading"><div><span class="eyebrow">Account security</span><h1>Change Password</h1></div></header><?php if($m=flash('success')):?><div class="alert alert-success" role="status"><?=e($m)?></div><?php endif;?><?php if($m=flash('error')):?><div class="alert alert-danger" role="alert"><?=e($m)?></div><?php endif;?><section class="surface-card security-card account-security-page"><div class="section-heading"><div><h2>Password and security</h2><p>Use at least 10 characters with uppercase, lowercase, number, and symbol.</p></div></div><form method="POST" class="form-stack" data-password-form><?=csrf_field()?><label>Current password<input class="form-control" type="password" name="current_password" autocomplete="current-password" required></label><label>New password<input class="form-control" type="password" name="new_password" autocomplete="new-password" data-password-input required></label><div class="password-requirements"><span data-rule="length">At least 10 characters</span><span data-rule="upper">One uppercase letter</span><span data-rule="lower">One lowercase letter</span><span data-rule="number">One number</span><span data-rule="symbol">One symbol</span></div><label>Confirm new password<input class="form-control" type="password" name="confirm_password" autocomplete="new-password" required></label><div class="form-actions"><button class="button-primary" type="submit"><?=ui_icon('lock')?>Change password</button></div></form></section></main></div><?php include "../includes/footer.php";?>
