<?php
require_once "../config/database.php";
require_once "../includes/functions.php";
require_role('admin');
$q=trim($_GET['q']??'');
$roleFilter=$_GET['role']??'all';if(!in_array($roleFilter,['all','client','staff','veterinarian','admin'],true))$roleFilter='all';
$userFilter=max(0,(int)($_GET['user_id']??0));
$period=$_GET['period']??'all';if(!in_array($period,['all','week','month','quarter','half_year','year'],true))$period='all';
$entityFilter=trim($_GET['entity']??'all');$entityOptions=[];$er=$conn->query("SELECT DISTINCT entity_type FROM audit_logs WHERE entity_type IS NOT NULL AND entity_type<>'' ORDER BY entity_type");while($er&&$row=$er->fetch_assoc())$entityOptions[]=$row['entity_type'];if($entityFilter!=='all'&&!in_array($entityFilter,$entityOptions,true))$entityFilter='all';
$where=[];$types='';$params=[];
if($q!==''){$like='%'.$q.'%';$where[]='(a.action LIKE ? OR a.details LIKE ? OR a.entity_type LIKE ? OR u.full_name LIKE ?)';$types.='ssss';array_push($params,$like,$like,$like,$like);}
if($roleFilter!=='all'){$where[]='u.role=?';$types.='s';$params[]=$roleFilter;}
if($userFilter){$where[]='a.actor_user_id=?';$types.='i';$params[]=$userFilter;}
if($entityFilter!=='all'){$where[]='a.entity_type=?';$types.='s';$params[]=$entityFilter;}
$periodSql=['week'=>'7 DAY','month'=>'1 MONTH','quarter'=>'3 MONTH','half_year'=>'6 MONTH','year'=>'1 YEAR'];if(isset($periodSql[$period]))$where[]='a.created_at>=DATE_SUB(NOW(),INTERVAL '.$periodSql[$period].')';
$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
[$page,$perPage,$offset]=pagination_values(6,24,[6,12,18,24,'full']);
$count=$conn->prepare("SELECT COUNT(*) c FROM audit_logs a LEFT JOIN users u ON a.actor_user_id=u.id $whereSql");if($types)$count->bind_param($types,...$params);$count->execute();$visibleCount=(int)$count->get_result()->fetch_assoc()['c'];
$stmt=$conn->prepare("SELECT a.*,u.full_name,u.role FROM audit_logs a LEFT JOIN users u ON a.actor_user_id=u.id $whereSql ORDER BY a.created_at DESC LIMIT $perPage OFFSET $offset");if($types)$stmt->bind_param($types,...$params);$stmt->execute();$rows=$stmt->get_result();
$summary=$conn->query("SELECT COUNT(*) total_logs,SUM(DATE(created_at)=CURDATE()) today_logs,SUM(actor_user_id IS NULL) system_logs,COUNT(DISTINCT actor_user_id) active_users FROM audit_logs")->fetch_assoc();
$roleCounts=array_fill_keys(['client','staff','veterinarian','admin'],0);$rcr=$conn->query("SELECT u.role,COUNT(*) c FROM audit_logs a JOIN users u ON a.actor_user_id=u.id GROUP BY u.role");while($rc=$rcr->fetch_assoc())if(isset($roleCounts[$rc['role']]))$roleCounts[$rc['role']]=(int)$rc['c'];
$roleAccents=['all'=>'#64748b','client'=>'#2f7d58','staff'=>'#a97820','veterinarian'=>'#2f6faa','admin'=>'#b24a76','system'=>'#64748b'];
$userSql="SELECT id,full_name,role FROM users WHERE role IN ('client','staff','veterinarian','admin')".($roleFilter!=='all'?" AND role='".$conn->real_escape_string($roleFilter)."'":'')." ORDER BY full_name";$users=$conn->query($userSql);
$title='Activity Logs';include "../includes/header.php";include "../includes/navbar.php";
?>
<div class="layout"><?php include "../includes/admin_sidebar.php";?><main class="content admin-activity-page" id="mainContent">
<header class="page-heading"><div><span class="eyebrow">Audit trail</span><h1>Activity Logs</h1></div><a class="button-secondary" href="<?=app_url('admin/faqs.php')?>"><?=ui_icon('help-circle')?>FAQ and access guide</a></header>
<section class="metric-grid compact-metrics"><article class="metric-card"><span class="metric-icon"><?=ui_icon('activity')?></span><div><small>Total logs</small><strong><?=intval($summary['total_logs'])?></strong><p>All retained events.</p></div></article><article class="metric-card"><span class="metric-icon info"><?=ui_icon('calendar-days')?></span><div><small>Today</small><strong><?=intval($summary['today_logs'])?></strong><p>Events recorded today.</p></div></article><article class="metric-card"><span class="metric-icon warning"><?=ui_icon('settings')?></span><div><small>System events</small><strong><?=intval($summary['system_logs'])?></strong><p>Events without a user actor.</p></div></article><article class="metric-card"><span class="metric-icon success"><?=ui_icon('users')?></span><div><small>Active actors</small><strong><?=intval($summary['active_users'])?></strong><p>Distinct users in the trail.</p></div></article></section>
<section class="surface-card data-toolbar activity-toolbar"><div class="filter-tabs activity-role-tabs"><a class="filter-tab role-all <?=$roleFilter==='all'?'active':''?>" style="--activity-accent:<?=e($roleAccents['all'])?>" href="?role=all&period=<?=e($period)?>">All users</a><?php foreach(['client'=>'Clients','staff'=>'Staff','veterinarian'=>'Veterinarians','admin'=>'Admins'] as $key=>$label):?><a class="filter-tab role-<?=$key?> <?=$roleFilter===$key?'active':''?>" style="--activity-accent:<?=e($roleAccents[$key])?>" href="?role=<?=$key?>&period=<?=e($period)?>"><?=e($label)?><b><?=$roleCounts[$key]?></b></a><?php endforeach;?></div><div class="toolbar-actions"><label class="entries-select">Show<select name="per_page"><?=render_per_page_options($perPage,[6,12,18,24,'full'])?></select></label><div class="view-toggle" data-view-toggle data-target="#activityFeedList" data-key="admin-activity-logs" data-default="list"><button type="button" data-view="list" aria-label="List view"><?=ui_icon('list')?></button><button type="button" data-view="grid" aria-label="Grid view"><?=ui_icon('grid')?></button></div></div></section>
<form class="surface-card activity-filter-form" method="GET"><input type="hidden" name="role" value="<?=e($roleFilter)?>"><input class="form-control" type="search" name="q" value="<?=e($q)?>" placeholder="Search action, details, or user" aria-label="Search activity"><select class="form-select" name="user_id" aria-label="User"><option value="0">All matching users</option><?php while($person=$users->fetch_assoc()):?><option value="<?=$person['id']?>" <?=$userFilter===$person['id']?'selected':''?>><?=e($person['full_name'])?> · <?=e(role_label($person['role']))?></option><?php endwhile;?></select><select class="form-select" name="entity" aria-label="Entity"><option value="all">All entities</option><?php foreach($entityOptions as $entity):?><option value="<?=e($entity)?>" <?=$entityFilter===$entity?'selected':''?>><?=e(ucwords(str_replace('_',' ',$entity)))?></option><?php endforeach;?></select><select class="form-select" name="period" aria-label="Date period"><option value="all" <?=$period==='all'?'selected':''?>>All dates</option><option value="week" <?=$period==='week'?'selected':''?>>Week</option><option value="month" <?=$period==='month'?'selected':''?>>Monthly</option><option value="quarter" <?=$period==='quarter'?'selected':''?>>Quarterly</option><option value="half_year" <?=$period==='half_year'?'selected':''?>>Twice a year</option><option value="year" <?=$period==='year'?'selected':''?>>Annual</option></select><button class="button-primary" type="submit">Search</button><a class="button-secondary" href="activity_logs.php?role=<?=e($roleFilter)?>">Clear</a></form>
<section class="surface-card activity-card" id="activityFeed"><div class="section-heading"><div><span class="eyebrow">Recent activity</span><h2><?=$visibleCount?> matching event<?= $visibleCount===1?'':'s' ?></h2><p>Newest events appear first.</p></div></div><div class="activity-feed view-list" id="activityFeedList"><?php if(!$rows->num_rows):?><div class="empty-state"><h2>No activity found</h2><p>Change the user or date filters.</p></div><?php endif;while($r=$rows->fetch_assoc()):$activityRole=(string)($r['role']?:'system');$activityAccent=$roleAccents[$activityRole]??$roleAccents['system'];$detail=['title'=>$r['action'],'eyebrow'=>'Audit event','fields'=>['Actor'=>$r['full_name']?:'System','Role'=>$r['role']?role_label($r['role']):'System','Entity'=>ucwords(str_replace('_',' ',$r['entity_type']?:'General')).($r['entity_id']?' #'.$r['entity_id']:''),'Date'=>date('M d, Y h:i A',strtotime($r['created_at'])),'Details'=>$r['details']?:'No additional details']];?><article class="activity-feed-item activity-role-<?=e(preg_replace('/[^a-z0-9_-]/','_',strtolower((string)($r['role']??'system'))))?> activity-type-<?=e(preg_replace('/[^a-z0-9_-]/','_',strtolower((string)($r['entity_type']??'system'))))?>" style="--activity-accent:<?=e($activityAccent)?>" data-record-detail='<?=e(json_encode($detail))?>'><span class="activity-feed-icon"><?=ui_icon('activity')?></span><div><header><h3><?=e($r['action'])?></h3><time><?=date('M d, Y h:i A',strtotime($r['created_at']))?></time></header><p><?=e($r['details']?:'No additional details were saved.')?></p><footer><span>Actor: <b><?=e($r['full_name']?:'System')?></b></span><span>Role: <b><?=e($r['role']?role_label($r['role']):'System')?></b></span><span>Entity: <b><?=e(ucwords(str_replace('_',' ',$r['entity_type']?:'General')))?><?=$r['entity_id']?' #'.intval($r['entity_id']):''?></b></span></footer></div></article><?php endwhile;?></div><?=render_pagination($page,$perPage,$visibleCount,['q'=>$q,'role'=>$roleFilter,'user_id'=>$userFilter,'entity'=>$entityFilter,'period'=>$period,'per_page'=>per_page_value($perPage),'_anchor'=>'activityFeed'])?></section>
</main></div><?php include "../includes/footer.php";?>
