<?php
require_once "../config/database.php";
require_once "../includes/functions.php";
require_role('admin');
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf_or_fail();$id=(int)($_POST['feedback_id']??0);
    $stmt=$conn->prepare("SELECT f.id,u.full_name FROM feedback f JOIN users u ON f.user_id=u.id WHERE f.id=?");$stmt->bind_param('i',$id);$stmt->execute();$item=$stmt->get_result()->fetch_assoc();
    if($item){$delete=$conn->prepare("UPDATE feedback SET comment=CONCAT('[Deleted] ',COALESCE(comment,'')) WHERE id=? AND comment NOT LIKE '[Deleted] %'");$delete->bind_param('i',$id);$delete->execute();log_action($conn,'Deleted client feedback','feedback',$id,'Feedback from '.$item['full_name'].' was removed from active views while its stored details were retained.');flash('success','Feedback deleted.');}else flash('error','Feedback record not found.');
    redirect_to('admin/feedback.php');
}
$q=trim($_GET['q']??'');$ratingFilter=trim($_GET['rating']??'all');if(!in_array($ratingFilter,['all','5','4','3','2','1'],true))$ratingFilter='all';
$feedbackFocusId=max(0,(int)($_GET['feedback_id']??0));
$period=$_GET['period']??'all';if(!in_array($period,['all','week','month','quarter','half_year','year'],true))$period='all';
$where=["f.comment NOT LIKE '[Deleted] %'"];$types='';$params=[];
if($q!==''){$like='%'.$q.'%';$where[]='(u.full_name LIKE ? OR f.comment LIKE ?)';$types.='ss';array_push($params,$like,$like);}
if($ratingFilter!=='all'){$where[]='f.rating=?';$types.='i';$params[]=(int)$ratingFilter;}
if($feedbackFocusId){$where[]='f.id=?';$types.='i';$params[]=$feedbackFocusId;}
$periodSql=['week'=>'7 DAY','month'=>'1 MONTH','quarter'=>'3 MONTH','half_year'=>'6 MONTH','year'=>'1 YEAR'];if(isset($periodSql[$period]))$where[]='f.created_at>=DATE_SUB(NOW(),INTERVAL '.$periodSql[$period].')';
$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
[$page,$perPage,$offset]=pagination_values(8,24,[8,16,24,'full']);
$count=$conn->prepare("SELECT COUNT(*) c FROM feedback f JOIN users u ON f.user_id=u.id $whereSql");if($types)$count->bind_param($types,...$params);$count->execute();$total=(int)$count->get_result()->fetch_assoc()['c'];
$hasVisitFeedback = $conn->query("SHOW COLUMNS FROM feedback LIKE 'appointment_id'")->num_rows > 0;
$visitSelect = $hasVisitFeedback ? 'a.id AS visit_id,p.name AS pet_name,COALESCE(a.scheduled_date,a.requested_date) AS visit_date' : 'NULL AS visit_id,NULL AS pet_name,NULL AS visit_date';
$visitJoin = $hasVisitFeedback ? 'LEFT JOIN appointments a ON a.id=f.appointment_id LEFT JOIN pets p ON p.id=a.pet_id' : '';
$stmt=$conn->prepare("SELECT f.*,u.full_name,u.email,u.profile_photo,$visitSelect FROM feedback f JOIN users u ON f.user_id=u.id $visitJoin $whereSql ORDER BY f.created_at DESC LIMIT $perPage OFFSET $offset");if($types)$stmt->bind_param($types,...$params);$stmt->execute();$rows=$stmt->get_result();
$summary=$conn->query("SELECT COUNT(*) total_feedback,ROUND(AVG(rating),1) average_rating,SUM(rating>=4) positive_feedback,SUM(rating<=2) low_feedback FROM feedback WHERE comment NOT LIKE '[Deleted] %'")->fetch_assoc();
$ratingCounts=array_fill_keys(['1','2','3','4','5'],0);$rc=$conn->query("SELECT rating,COUNT(*) c FROM feedback WHERE comment NOT LIKE '[Deleted] %' GROUP BY rating");while($rr=$rc->fetch_assoc())$ratingCounts[(string)$rr['rating']]=(int)$rr['c'];
$title='Feedback';include "../includes/header.php";include "../includes/navbar.php";
?>
<div class="layout"><?php include "../includes/admin_sidebar.php";?><main class="content admin-feedback-page" id="mainContent">
<header class="page-heading"><div><span class="eyebrow">Client feedback</span><h1>Feedback Management</h1></div></header>
<?php if($m=flash('success')):?><div class="alert alert-success"><?=e($m)?></div><?php endif;?><?php if($m=flash('error')):?><div class="alert alert-danger"><?=e($m)?></div><?php endif;?>
<section class="metric-grid compact-metrics"><article class="metric-card"><span class="metric-icon"><?=ui_icon('message')?></span><div><small>Total feedback</small><strong><?=intval($summary['total_feedback'])?></strong><p>All client responses.</p></div></article><article class="metric-card"><span class="metric-icon info"><?=ui_icon('chart')?></span><div><small>Average rating</small><strong><?=e($summary['average_rating']?:'0')?>/5</strong><p>Across all submissions.</p></div></article><article class="metric-card"><span class="metric-icon success"><?=ui_icon('check')?></span><div><small>Positive ratings</small><strong><?=intval($summary['positive_feedback'])?></strong><p>Four or five stars.</p></div></article><article class="metric-card"><span class="metric-icon warning"><?=ui_icon('alert')?></span><div><small>Low ratings</small><strong><?=intval($summary['low_feedback'])?></strong><p>One or two stars.</p></div></article></section>
<?php $ratingStars=['5'=>'★★★★★','4'=>'★★★★','3'=>'★★★','2'=>'★★','1'=>'★']; ?>
<section class="surface-card data-toolbar feedback-filter-row feedback-filter-panel"><div class="feedback-left-controls"><div class="filter-tabs feedback-filter-tabs"><a class="filter-tab rating-all <?=$ratingFilter==='all'?'active':''?>" href="?rating=all&period=<?=e($period)?>&q=<?=urlencode($q)?>">All <b><?=intval($summary['total_feedback'])?></b></a><?php foreach(['5','4','3','2','1'] as $rating):?><a class="filter-tab rating-<?=$rating?> <?=$ratingFilter===$rating?'active':''?>" href="?rating=<?=$rating?>&period=<?=e($period)?>&q=<?=urlencode($q)?>"?><?=$ratingStars[$rating]?> <b><?=$ratingCounts[$rating]?></b></a><?php endforeach;?></div></div><div class="feedback-filter-actions toolbar-actions"><label class="entries-select">Show<select name="per_page" form="feedbackFilterForm" onchange="document.getElementById('feedbackFilterForm').requestSubmit()"><?=render_per_page_options($perPage,[8,16,24,'full'])?></select></label></div></section>
<form class="surface-card data-search-bar feedback-search" id="feedbackFilterForm" data-search-bound="1" method="GET"><input type="hidden" name="rating" value="<?=e($ratingFilter)?>"><input type="search" name="q" value="<?=e($q)?>" placeholder="Search client or feedback"><label class="feedback-period-select"><select class="form-select" name="period" aria-label="Date period"><option value="all" <?=$period==='all'?'selected':''?>>All dates</option><option value="week" <?=$period==='week'?'selected':''?>>Week</option><option value="month" <?=$period==='month'?'selected':''?>>Monthly</option><option value="quarter" <?=$period==='quarter'?'selected':''?>>Quarterly</option><option value="half_year" <?=$period==='half_year'?'selected':''?>>Twice a year</option><option value="year" <?=$period==='year'?'selected':''?>>Annual</option></select></label><button class="button-primary" type="submit">Search</button><a class="button-secondary" href="?rating=<?=e($ratingFilter)?>&period=<?=e($period)?>&per_page=<?=e(per_page_value($perPage))?>">Clear</a></form>
<section class="feedback-collection view-grid" id="feedbackResponses"><?php if(!$rows->num_rows):?><div class="empty-state surface-card"><h2>No feedback found</h2><p>Change the score, date period, or search.</p></div><?php endif;while($r=$rows->fetch_assoc()):$detail=['title'=>$r['full_name'].' feedback','eyebrow'=>$r['rating'].' of 5 stars','fields'=>['Client'=>$r['full_name'],'Email'=>$r['email'],'Rating'=>$r['rating'].' / 5','Submitted'=>date('M d, Y h:i A',strtotime($r['created_at'])),'Feedback'=>$r['comment']?:'No written comment']];if($r['visit_id']){$detail['fields']['Visit']='#'.$r['visit_id'];$detail['fields']['Pet']=$r['pet_name'];$detail['fields']['Visit date']=$r['visit_date']?date('M d, Y',strtotime($r['visit_date'])):'Not recorded';}?><article id="feedback<?=$r['id']?>" class="surface-card feedback-card <?=$r['rating']<=2?'priority':''?>" data-rating="<?=intval($r['rating'])?>" data-record-detail='<?=e(json_encode($detail))?>'><header><?=user_avatar_markup($r,'feedback-avatar')?><div><h2><?=e($r['full_name'])?></h2><p><?=date('M d, Y h:i A',strtotime($r['created_at']))?></p></div><span class="rating-badge"><?=intval($r['rating'])?> / 5</span></header><blockquote><?=e($r['comment']?:'No written comment.')?></blockquote><?php if($r['visit_id']):?><p>Visit #<?=intval($r['visit_id'])?> &middot; <?=e($r['pet_name'])?><?php if($r['visit_date']):?> &middot; <?=e(date('M d, Y',strtotime($r['visit_date'])))?><?php endif;?></p><?php endif;?><footer><?php if($r['rating']<=2):?><span>Needs attention</span><?php endif;?><form method="POST" data-confirm-message="Delete this feedback from active views?"><?=csrf_field()?><input type="hidden" name="feedback_id" value="<?=$r['id']?>"><button class="button-danger" type="submit"><?=ui_icon('trash')?>Delete</button></form></footer></article><?php endwhile;?></section><?=render_pagination($page,$perPage,$total,['q'=>$q,'rating'=>$ratingFilter,'period'=>$period,'per_page'=>per_page_value($perPage),'feedback_id'=>$feedbackFocusId?:null,'_anchor'=>'feedbackResponses'])?>
<?php if($feedbackFocusId):?><script>document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>document.getElementById('feedback<?=$feedbackFocusId?>')?.click(),100));</script><?php endif;?>
</main></div><?php include "../includes/footer.php";?>
