<?php
require_once "../config/database.php";
require_once "../includes/functions.php";
require_role('admin');
ensure_review_workflow_schema($conn);
$editableFields=['name'=>'Pet Name','species'=>'Species','breed'=>'Breed','sex'=>'Sex','birth_date'=>'Birth Date','weight'=>'Weight','color'=>'Color / Markings','allergies'=>'Allergies','critical_notes'=>'Critical Notes','notes'=>'Care Notes'];
$approvalReasons=['checked_in_person'=>'Checked by a veterinarian in person','valid_proof'=>'Valid supporting proof was attached','clinic_record'=>'Clinic records confirm the requested change','owner_identity_verified'=>'Owner and pet identity were verified'];
$rejectionReasons=['proof_unreadable'=>'Supporting proof is unreadable','proof_not_valid'=>'Supporting proof is not valid or sufficient','vet_check_required'=>'A veterinarian must check the pet in person','information_mismatch'=>'Submitted information does not match clinic records'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf_or_fail();$id=(int)($_POST['request_id']??0);$action=$_POST['action']??'';$notes=trim($_POST['admin_notes']??'');
    $stmt=$conn->prepare("SELECT er.*,p.name pet_name FROM edit_requests er JOIN pets p ON er.pet_id=p.id WHERE er.id=? LIMIT 1");$stmt->bind_param('i',$id);$stmt->execute();$req=$stmt->get_result()->fetch_assoc();
    if(!$req){flash('error','Edit request not found.');redirect_to('admin/pet_edit_requests.php');}
    if($action==='approve_request' || $action==='reject_request'){
        $status=$action==='approve_request'?'approved':'rejected';
        $reasonKey=trim($_POST[$status==='approved'?'approval_reason':'rejection_reason']??'');
        $reasonMap=$status==='approved'?$approvalReasons:$rejectionReasons;
        if(!isset($reasonMap[$reasonKey])){flash('error','Choose a valid review reason before continuing.');redirect_to('admin/pet_edit_requests.php');}
        $notes=$reasonMap[$reasonKey].($notes!==''?' — '.$notes:'');
        if($req['status']!=='pending'){flash('error','Only pending requests can be reviewed.');redirect_to('admin/pet_edit_requests.php');}
        if($status==='approved' && $req['field_name']==='allergies' && $req['vet_approval_status']!=='approved'){flash('error','Allergy changes require veterinarian approval before administrator approval.');redirect_to('admin/pet_edit_requests.php');}
        if($status==='approved'){
            $field=$req['field_name'];if(!isset($editableFields[$field])){flash('error','This field is not approved for edit requests.');redirect_to('admin/pet_edit_requests.php');}
            $update=$conn->prepare("UPDATE pets SET `$field`=?,last_updated_by=?,updated_at=NOW() WHERE id=?");$admin=(int)current_user_id();$update->bind_param('sii',$req['new_value'],$admin,$req['pet_id']);$update->execute();
            notify_user($conn,$req['client_id'],'Pet Edit Approved','Your requested change for '.$editableFields[$field].' was approved.','record',null);log_action($conn,'Approved pet edit request','pet',$req['pet_id'],$editableFields[$field].' updated.');
        }else{notify_user($conn,$req['client_id'],'Pet Edit Rejected','Your requested change for '.($editableFields[$req['field_name']]??$req['field_name']).' was rejected. You may appeal with supporting proof.','record',null);log_action($conn,'Rejected pet edit request','pet',$req['pet_id'],($editableFields[$req['field_name']]??$req['field_name']).' rejected.');}
        $review=$conn->prepare("UPDATE edit_requests SET status=?,admin_notes=?,reviewed_at=NOW() WHERE id=?");$review->bind_param('ssi',$status,$notes,$id);$review->execute();flash('success','Pet edit request reviewed.');
    }elseif($action==='accept_appeal' || $action==='reject_appeal'){
        if($action==='reject_appeal' && $notes===''){flash('error','A review note is required before rejecting an appeal.');redirect_to('admin/pet_edit_requests.php');}
        if($req['appeal_status']!=='pending'){flash('error','This appeal is no longer pending.');redirect_to('admin/pet_edit_requests.php');}
        if($action==='accept_appeal'){$stmt=$conn->prepare("UPDATE edit_requests SET status='pending',appeal_status='approved',admin_notes=? WHERE id=?");$stmt->bind_param('si',$notes,$id);$stmt->execute();notify_user($conn,$req['client_id'],'Pet Edit Appeal Accepted','Your appeal was accepted and returned to the review queue.','record',null);flash('success','Appeal accepted and request returned to pending review.');}
        else{$stmt=$conn->prepare("UPDATE edit_requests SET appeal_status='rejected',admin_notes=? WHERE id=?");$stmt->bind_param('si',$notes,$id);$stmt->execute();notify_user($conn,$req['client_id'],'Pet Edit Appeal Rejected','Your pet edit appeal was rejected after review.','record',null);flash('success','Appeal rejected.');}
        log_action($conn,$action==='accept_appeal'?'Accepted pet edit appeal':'Rejected pet edit appeal','edit_request',$id,$notes);
    }
    redirect_to('admin/pet_edit_requests.php');
}
$status=$_GET['status']??'all';if(!in_array($status,['all','pending','approved','rejected','appealed'],true))$status='all';$q=trim($_GET['q']??'');[$page,$perPage,$offset]=pagination_values(4,16,[4,8,12,16,'full']);
$where=[];$types='';$params=[];if($status==='appealed')$where[]="er.appeal_status='pending'";elseif($status!=='all'){$where[]='er.status=?';$types.='s';$params[]=$status;}if($q!==''){$like='%'.$q.'%';$where[]='(u.full_name LIKE ? OR p.name LIKE ? OR er.field_name LIKE ? OR er.old_value LIKE ? OR er.new_value LIKE ?)';$types.='sssss';array_push($params,$like,$like,$like,$like,$like);}$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
$count=$conn->prepare("SELECT COUNT(*) c FROM edit_requests er JOIN pets p ON er.pet_id=p.id JOIN users u ON er.client_id=u.id $whereSql");if($types)$count->bind_param($types,...$params);$count->execute();$total=(int)$count->get_result()->fetch_assoc()['c'];
$stmt=$conn->prepare("SELECT er.*,p.name pet_name,p.species,p.pet_photo,u.full_name requester_name,u.email requester_email,v.full_name vet_name FROM edit_requests er JOIN pets p ON er.pet_id=p.id JOIN users u ON er.client_id=u.id LEFT JOIN users v ON er.vet_approved_by=v.id $whereSql ORDER BY er.appeal_status='pending' DESC,FIELD(er.status,'pending','rejected','approved'),er.created_at DESC LIMIT $perPage OFFSET $offset");if($types)$stmt->bind_param($types,...$params);$stmt->execute();$rows=[];$res=$stmt->get_result();while($r=$res->fetch_assoc())$rows[]=$r;
$summary=$conn->query("SELECT COUNT(*) total,SUM(status='pending') pending,SUM(status='approved') approved,SUM(status='rejected') rejected,SUM(appeal_status='pending') appealed FROM edit_requests")->fetch_assoc();
$title='Pet Edit Requests';include "../includes/header.php";include "../includes/navbar.php";
?>
<div class="layout"><?php include "../includes/admin_sidebar.php";?><main class="content admin-pet-edit-requests-page" id="mainContent">
<header class="page-heading"><div><span class="eyebrow">Pet records</span><h1>Pet Edit Requests</h1></div></header>
<?php if($m=flash('success')):?><div class="alert alert-success"><?=e($m)?></div><?php endif;?><?php if($m=flash('error')):?><div class="alert alert-danger"><?=e($m)?></div><?php endif;?>
<section class="surface-card data-toolbar pet-edit-toolbar"><div class="filter-tabs"><?php foreach(['all'=>'All','pending'=>'Pending','approved'=>'Approved','rejected'=>'Rejected','appealed'=>'Appeals'] as $key=>$label):?><a class="filter-tab filter-<?=e($key)?> <?=$status===$key?'active':''?>" href="?status=<?=$key?>&q=<?=urlencode($q)?>&per_page=<?=e(per_page_value($perPage))?>"><?=e($label)?><b><?=intval($summary[$key==='all'?'total':$key]??0)?></b></a><?php endforeach;?></div><form method="GET" class="toolbar-actions compact-page-size"><input type="hidden" name="status" value="<?=e($status)?>"><input type="hidden" name="q" value="<?=e($q)?>"><label class="entries-select">Show<select name="per_page" aria-label="Pet edit requests per page"><?=render_per_page_options($perPage,[4,8,12,16,'full'])?></select></label></form></section>
<form class="surface-card data-search-bar" method="GET"><input type="hidden" name="status" value="<?=e($status)?>"><input type="search" name="q" value="<?=e($q)?>" placeholder="Search pet, requester, field, or value"><button class="button-primary">Search</button><?php if($q!==''):?><a class="button-secondary" href="?status=<?=e($status)?>">Clear</a><?php endif;?></form>
<div class="edit-request-grid view-grid" id="editRequestQueue"><?php if(!$rows):?><div class="empty-state surface-card"><h2>No requests found</h2><p>Try another filter or search.</p></div><?php endif;foreach($rows as $r):$fieldLabel=$editableFields[$r['field_name']]??ucwords(str_replace('_',' ',$r['field_name']));$detail=['title'=>$r['pet_name'].' · '.$fieldLabel,'eyebrow'=>'Requested by '.$r['requester_name'],'fields'=>['Old value'=>$r['old_value'],'Requested value'=>$r['new_value'],'Proof note'=>$r['proof_note']?:'No note','Status'=>ucfirst($r['status']),'Veterinarian consultation'=>ucwords(str_replace('_',' ',$r['vet_approval_status'])).($r['vet_name']?' by '.$r['vet_name']:''),'Appeal'=>ucwords(str_replace('_',' ',$r['appeal_status'])),'Clinic note'=>$r['admin_notes']?:'No note']];?>
<article class="surface-card edit-request-card" data-record-detail='<?=e(json_encode($detail))?>'><header><?=pet_avatar_markup($r,'entity-avatar')?><div><span class="eyebrow"><?=e($fieldLabel)?></span><h2><?=e($r['pet_name'])?></h2><p>Requested by <?=e($r['requester_name'])?></p></div><?=badge($r['status'])?></header><div class="change-comparison"><div><small>Current</small><p><?=e($r['old_value']?:'Not recorded')?></p></div><span><?=ui_icon('arrow-right')?></span><div><small>Requested</small><p><?=e($r['new_value'])?></p></div></div><div class="request-evidence"><span><b>Proof</b><?php if($r['proof_path']):?><a class="button-secondary proof-view-button" data-detail-bypass target="_blank" rel="noopener" href="<?=e(app_url($r['proof_path']))?>">View proof</a><?php else:?><small>No proof uploaded</small><?php endif;?></span><span><b>Vet consultation</b><small><?=e(ucwords(str_replace('_',' ',$r['vet_approval_status'])))?><?=$r['vet_name']?' · '.e($r['vet_name']):''?></small></span><?php if($r['appeal_status']!=='none'):?><span><b>Appeal</b><small><?=e(ucwords(str_replace('_',' ',$r['appeal_status'])))?></small><?php if($r['appeal_proof_path']):?><a class="button-secondary proof-view-button" data-detail-bypass target="_blank" rel="noopener" href="<?=e(app_url($r['appeal_proof_path']))?>">View appeal proof</a><?php endif;?></span><?php endif;?></div><?php if($r['status']!=='pending' && trim((string)($r['admin_notes'] ?? ''))!==''):?><div class="review-ui-review-reason"><b><?=e(ucfirst($r['status']))?> reason</b><p><?=e($r['admin_notes'])?></p></div><?php endif;?>
<?php $waitingVetConsult=($r['vet_approval_status']??'not_required')==='pending';?><?php if($r['status']==='pending'):?><div class="request-review-zone"><?php if($waitingVetConsult):?><div class="vet-consult-waiting"><span class="vet-consult-waiting-icon"><?=ui_icon('clock')?></span><div class="vet-consult-waiting-copy"><b>Waiting for veterinarian consultation</b><p>Administrator approval can continue after the veterinarian review is approved.</p></div></div><?php else:?><div class="review-decision-grid"><form method="POST" class="request-review-form approve-review-form"><?=csrf_field()?><input type="hidden" name="request_id" value="<?=$r['id']?>"><label>Approval reason<select class="form-select" name="approval_reason" required><option value="">Choose</option><?php foreach($approvalReasons as $key=>$label):?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select></label><label>Optional note<textarea class="form-control" name="admin_notes" rows="2" placeholder="Add a short clinic note"></textarea></label><button class="button-primary pet-edit-approve-button" name="action" value="approve_request" data-confirm-message="Approve this pet profile change using the selected reason?"<?=$waitingVetConsult?' title="Waiting for veterinarian consultation"':''?>>Approve</button></form><form method="POST" class="request-review-form reject-review-form"><?=csrf_field()?><input type="hidden" name="request_id" value="<?=$r['id']?>"><label>Rejection reason<select class="form-select" name="rejection_reason" required><option value="">Choose</option><?php foreach($rejectionReasons as $key=>$label):?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select></label><label>Optional note<textarea class="form-control" name="admin_notes" rows="2" placeholder="Add context for the client"></textarea></label><button class="button-danger" name="action" value="reject_request" data-confirm-message="Reject this pet profile change using the selected reason?">Reject</button></form></div><?php endif;?></div><?php endif;?>
<?php if($r['appeal_status']==='pending'):?><form method="POST" class="request-review-form appeal-review"><?=csrf_field()?><input type="hidden" name="request_id" value="<?=$r['id']?>"><label>Appeal review note<textarea class="form-control" name="admin_notes"><?=e($r['appeal_note'])?></textarea></label><div class="form-actions"><button class="button-danger" name="action" value="reject_appeal">Reject appeal</button><button class="button-primary" name="action" value="accept_appeal">Return to review</button></div></form><?php endif;?>
</article><?php endforeach;?></div><?=render_pagination($page,$perPage,$total,['status'=>$status,'q'=>$q,'per_page'=>per_page_value($perPage),'_anchor'=>'editRequestQueue'])?>


<script>document.querySelectorAll('.appeal-review').forEach(form=>{const note=form.querySelector('textarea[name="admin_notes"]');form.addEventListener('submit',event=>{if(event.submitter?.value==='reject_appeal'&&!note.value.trim()){event.preventDefault();note.required=true;note.setCustomValidity('Enter a review note before rejecting the appeal.');note.reportValidity();note.addEventListener('input',()=>note.setCustomValidity(''),{once:true});}});});</script>
</main></div><?php include "../includes/footer.php";?>
