<?php
require_once "../config/database.php";
require_once "../includes/functions.php";
require_role("admin");
$totalPets=(int)$conn->query("SELECT COUNT(*) c FROM pets WHERE verification_status='approved'")->fetch_assoc()['c'];$totalClients=(int)$conn->query("SELECT COUNT(*) c FROM users WHERE role='client'")->fetch_assoc()['c'];$totalRecords=(int)$conn->query("SELECT COUNT(*) c FROM medical_records")->fetch_assoc()['c'];$totalAppointments=(int)$conn->query("SELECT COUNT(*) c FROM appointments")->fetch_assoc()['c'];
function report_overview_html($rows,$kind){
    if(!$rows)return '<p class="empty-copy">No related records found.</p>';
    $html='<div class="dashboard-detail-list">';
    foreach($rows as $r){
        if($kind==='client'){$title=$r['full_name'];$meta=ucwords(str_replace('_',' ',$r['status'])).' · '.date('M d, Y',strtotime($r['created_at']));}
        elseif($kind==='pet'){$title=$r['name'].' · '.$r['full_name'];$meta=$r['species'].' · '.date('M d, Y',strtotime($r['created_at']));}
        elseif($kind==='record'){$title=$r['pet_name'].' · '.($r['diagnosis']?:'Clinical record');$meta=date('M d, Y',strtotime($r['visit_date']));}
        else{$title=$r['pet_name'].' · '.$r['full_name'];$when=$r['scheduled_date']?:$r['requested_date'];$meta=ucfirst($r['status']).' · '.date('M d, Y h:i A',strtotime($when));}
        $html.='<article class="dashboard-detail-item"><span><b>'.e($title).'</b><small>'.e($meta).'</small></span></article>';
    }
    return $html.'</div>';
}
$clientOverview=[];$q=$conn->query("SELECT id,full_name,status,created_at FROM users WHERE role='client' ORDER BY created_at DESC,id DESC LIMIT 8");while($q&&$r=$q->fetch_assoc())$clientOverview[]=$r;
$petOverview=[];$q=$conn->query("SELECT p.id,p.name,p.species,p.created_at,u.full_name FROM pets p JOIN users u ON p.owner_id=u.id WHERE p.verification_status='approved' ORDER BY p.created_at DESC,p.id DESC LIMIT 8");while($q&&$r=$q->fetch_assoc())$petOverview[]=$r;
$recordOverview=[];$q=$conn->query("SELECT m.id,m.pet_id,m.visit_date,m.diagnosis,p.name pet_name FROM medical_records m JOIN pets p ON m.pet_id=p.id ORDER BY m.visit_date DESC,m.id DESC LIMIT 8");while($q&&$r=$q->fetch_assoc())$recordOverview[]=$r;
$appointmentOverview=[];$q=$conn->query("SELECT a.id,a.status,a.requested_date,a.scheduled_date,p.name pet_name,u.full_name FROM appointments a JOIN pets p ON a.pet_id=p.id JOIN users u ON a.owner_id=u.id ORDER BY COALESCE(a.scheduled_date,a.requested_date) DESC,a.id DESC LIMIT 8");while($q&&$r=$q->fetch_assoc())$appointmentOverview[]=$r;
$clientOverviewHtml=report_overview_html($clientOverview,'client');$petOverviewHtml=report_overview_html($petOverview,'pet');$recordOverviewHtml=report_overview_html($recordOverview,'record');$appointmentOverviewHtml=report_overview_html($appointmentOverview,'appointment');
$title='Reports and Export';include "../includes/header.php";include "../includes/navbar.php";
?>
<div class="layout"><?php include "../includes/admin_sidebar.php";?><main class="content admin-reports-page" id="mainContent">
<header class="page-heading"><div><span class="eyebrow">Clinic documents</span><h1>Reports and Export</h1></div></header>
<section class="metric-grid"><button type="button" class="metric-card" data-record-detail='<?=e(json_encode(['title'=>'Registered clients','eyebrow'=>'Recent client accounts','html'=>$clientOverviewHtml,'action_url'=>app_url('admin/report_clients.php'),'action_label'=>'Open Client and Pet Directory']))?>'><span class="metric-icon"><?=ui_icon('users')?></span><div><small>Clients</small><strong><?=$totalClients?></strong><p>Open a recent client account overview.</p></div></button><button type="button" class="metric-card" data-record-detail='<?=e(json_encode(['title'=>'Approved pets','eyebrow'=>'Recent verified pet profiles','html'=>$petOverviewHtml]))?>'><span class="metric-icon info"><?=ui_icon('paw')?></span><div><small>Approved pets</small><strong><?=$totalPets?></strong><p>Open a recent approved pet overview.</p></div></button><button type="button" class="metric-card" data-record-detail='<?=e(json_encode(['title'=>'Medical records','eyebrow'=>'Recent clinical records','html'=>$recordOverviewHtml]))?>'><span class="metric-icon success"><?=ui_icon('file')?></span><div><small>Medical records</small><strong><?=$totalRecords?></strong><p>Open recent clinical record summaries.</p></div></button><button type="button" class="metric-card" data-record-detail='<?=e(json_encode(['title'=>'Appointments','eyebrow'=>'Recent appointment records','html'=>$appointmentOverviewHtml,'action_url'=>app_url('admin/report_appointments.php'),'action_label'=>'Open Appointment Report']))?>'><span class="metric-icon warning"><?=ui_icon('calendar-days')?></span><div><small>Appointments</small><strong><?=$totalAppointments?></strong><p>Open recent appointment summaries.</p></div></button></section>
<section class="surface-card reports-section report-group-section"><div class="section-heading report-group-heading"><div><span class="eyebrow">Printable reports</span><h2>Open a report</h2></div></div><div class="report-card-grid">
<article class="report-action-card"><span><?=ui_icon('file')?></span><div><h3>Pet Medical Report</h3><p>Pet profile, owner, medical history, vaccinations, and emergency notes.</p></div><form action="report_pet.php" method="GET"><select class="form-select" name="pet_id" required><option value="">Select approved pet</option><?php $pets=$conn->query("SELECT p.id,p.name,u.full_name FROM pets p JOIN users u ON p.owner_id=u.id WHERE p.verification_status='approved' ORDER BY p.name");while($p=$pets->fetch_assoc()):?><option value="<?=$p['id']?>"><?=e($p['name'])?> · <?=e($p['full_name'])?></option><?php endwhile;?></select><button class="button-primary" type="submit">Open report</button></form></article>
<article class="report-action-card"><span><?=ui_icon('calendar-days')?></span><div><h3>Appointment Report</h3><p>Appointment schedule and status totals for a selected date range.</p></div><form action="report_appointments.php" method="GET"><div class="form-grid-two"><label>From<input class="form-control" type="date" name="from" value="<?=date('Y-m-01')?>"></label><label>To<input class="form-control" type="date" name="to" value="<?=date('Y-m-t')?>"></label></div><button class="button-primary" type="submit">Open report</button></form></article>
<article class="report-action-card"><span><?=ui_icon('syringe')?></span><div><h3>Vaccination Due Report</h3><p>Pets with upcoming or overdue vaccination follow-ups.</p></div><form action="report_vaccinations.php" method="GET"><label>Due within<select class="form-select" name="days"><option value="30">30 days</option><option value="60" selected>60 days</option><option value="90">90 days</option><option value="365">1 year</option></select></label><button class="button-primary" type="submit">Open report</button></form></article>
<article class="report-action-card"><span><?=ui_icon('users')?></span><div><h3>Client and Pet Directory</h3><p>Printable directory of clients, contact details, and registered pets.</p></div><a class="button-primary" href="report_clients.php">Open report</a></article>
<article class="report-action-card"><span><?=ui_icon('qr')?></span><div><h3>QR Emergency Report</h3><p>Emergency profile using a valid active pet QR token.</p></div><form action="report_emergency.php" method="GET"><label>QR token<input class="form-control" name="token" value="" required></label><button class="button-primary" type="submit">Open report</button></form></article>
<article class="report-action-card"><span><?=ui_icon('chart')?></span><div><h3>Clinic Analytics</h3><p>Appointments, species, records, vaccinations, feedback, and clinic activity.</p></div><a class="button-primary" href="report_analytics.php">Open report</a></article>
</div></section>
<section class="surface-card reports-section report-group-section" id="exports"><div class="section-heading report-group-heading"><div><span class="eyebrow">Structured data</span><h2>CSV exports</h2></div></div><div class="export-card-grid"><?php foreach([['clients','users','Clients','Client contact and account details'],['pets','paw','Pets','Pet profiles and verification information'],['appointments','calendar-days','Appointments','Requested and scheduled appointment records'],['records','file','Medical records','Diagnoses, treatment, prescriptions, and notes']] as [$type,$icon,$label,$description]):?><a class="export-action-card" href="<?=app_url('api/export_csv.php?type='.$type)?>"><span><?=ui_icon($icon)?></span><div><h3><?=e($label)?></h3><p><?=e($description)?></p></div><b><?=ui_icon('download')?>Download CSV</b></a><?php endforeach;?></div></section>
</main></div><?php include "../includes/footer.php";?>
