<?php
function report_header($title, $subtitle='') {
    $date = date('F d, Y h:i A');
    $user = function_exists('current_user_record') ? current_user_record($GLOBALS['conn'] ?? null) : null;
    $generatedBy = $user
        ? trim((string)$user['full_name']) . ' (' . ucwords(str_replace('_', ' ', (string)$user['role'])) . ')'
        : 'Vetrix System';
    $reportType = trim((string)preg_replace('/[^A-Za-z0-9]+/', '_', trim((string)$title)), '_');
    $safeTitle = clean_report($title);
    $safeSubtitle = clean_report($subtitle);
    $safeType = clean_report($reportType);
    $safeGeneratedBy = clean_report($generatedBy);
    $safeDate = clean_report($date);
    return "
    <div class='print-header'>
        <div>
            <div class='print-title'>Vetrix</div>
            <div>Clinic Management System</div>
            <div class='small text-muted'>Clinic Management Report</div>
        </div>
        <div class='print-header-meta'>
            <div class='report-type-label'>Report Type: {$safeType}</div>
            <h2>{$safeTitle}</h2>
            <div>{$safeSubtitle}</div>
            <div class='small text-muted'>Generated By: {$safeGeneratedBy}</div>
            <div class='small text-muted'>Generated: {$safeDate}</div>
        </div>
    </div>";
}

function report_actions() {
    return "<div class='no-print-actions report-action-buttons'>
        <button type='button' onclick='saveVetrixReportPdf()' class='button-primary'>Print / Save PDF</button>
        <button type='button' data-smart-back onclick='if(window.vetrixSmartBack){event.preventDefault();vetrixSmartBack();}else history.back();' class='button-secondary'>Back</button>
    </div>";
}

function clean_report($value) {
    return htmlspecialchars($value ?? '', ENT_QUOTES, 'UTF-8');
}
?>
